"""Render out/report.html from the collected findings.

    python collect_findings.py   # gather statistics into out/findings.json
    python report_page.py        # render the page

Chart primitives and data loading live in build_report.py; this module holds the
page copy and markup. Numbers are interpolated from the JSON so the prose and
the data cannot drift apart.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_report import (  # noqa: E402
    FINDINGS, FOLLOWUPS, PLACEBO, SEG_LABEL, cohesion_summary, esc, legend,
    ordinal, table,
    top_templates,
    build_volume_chart, build_templating_chart, build_state_chart,
    build_placebo_charts,
)
from cfpb_inspect import config  # noqa: E402

# ITS results transcribed from out/report.md, generated by `cli.py report` over
# the full extract. Kept literal so this page renders in seconds rather than
# refitting ~5,900 negative-binomial models; out/report.md remains the source of
# truth and can be diffed against these values.
ITS = [
    ("credit_reporting", 166, +21.8, "0.010", 27.9, "not distinctive"),
    ("debt_collection", 157, -22.1, "0.00003", 2.5, "not distinctive"),
    ("mortgage", 176, -6.5, "0.285", 27.3, "not distinctive"),
    ("card", 176, +34.8, "&lt;0.001", 82.0, "suggestive"),
    ("student_loan", 173, -2.1, "0.922", 1.5, "not distinctive"),
    ("consumer_loan", 173, -5.3, "0.565", 6.6, "not distinctive"),
    ("all six combined", 176, +36.1, "&lt;0.001", 25.9, "not distinctive"),
]

BREAKS = [
    ("credit_reporting", "2017-05", "+285%", "Taxonomy rename one week earlier"),
    ("credit_reporting", "2020-04", "+251%", "COVID onset"),
    ("credit_reporting", "2022-05", "+210%",
     "Medical-debt removal 61d away; ChatGPT 213d"),
    ("credit_reporting", "2024-01", "+262%", "Unexplained"),
    ("debt_collection", "2023-12", "+331%", "Unexplained"),
    ("student_loan", "2023-06", "+214%",
     "Biden v. Nebraska 29d away; GPT-4 79d"),
    ("card", "2022-10", "+100%", "Precedes ChatGPT by 60 days"),
    ("all six combined", "2024-06", "+304%", "Unexplained"),
]

CHANNEL = [
    ("Web", 898465, 2119643, 95.141, 97.959),
    ("Postal mail", 5259, 8555, 0.562, 0.400),
    ("Phone", 24931, 26907, 2.688, 1.332),
    ("Referral", 14218, 6569, 1.608, 0.309),
]

BURSTS = [
    ("EdFinancial", "2022-09", "37x", "FedLoan/PHEAA portfolio transfer"),
    ("MOHELA", "2022-10", "27x", "FedLoan/PHEAA portfolio transfer"),
    ("Navient", "2017-01", "18x", "CFPB enforcement suit, 3 days earlier"),
    ("Navient", "2024-09", "6.5x", "CFPB ban and $120M order, 3 days earlier"),
    ("John C Heath, Attorney at Law", "2024-12", "228x",
     "Credit-repair firm (Lexington Law). Unexplained"),
    ("Ameritech Financial", "2018-07", "164x",
     "Student debt-relief operation. Unexplained"),
]

CSS = """
:root{
  --bg:#f6f7f8; --surface:#ffffff; --surface-2:#eef1f3;
  --ink:#14171b; --ink-2:#4b5359; --ink-3:#767f86;
  --rule:#dfe3e6;
  --accent:#1c5cab; --accent-2:#2a78d6;
  --flag:#b4322f; --ok:#12684a;
  --s1:#2a78d6; --s2:#eb6834; --s3:#1baf7a;
  --grid:#e3e7ea; --event:#a8b0b6;
  color-scheme:light;
}
@media (prefers-color-scheme:dark){
  :root:not([data-theme="light"]){
    --bg:#14171a; --surface:#1c2023; --surface-2:#22272b;
    --ink:#f2f4f5; --ink-2:#b3bbc1; --ink-3:#8b949b;
    --rule:#2c3236;
    --accent:#6da7ec; --accent-2:#3987e5;
    --flag:#e66767; --ok:#3fae7f;
    --s1:#3987e5; --s2:#d95926; --s3:#199e70;
    --grid:#282e32; --event:#5a636a;
    color-scheme:dark;
  }
}
:root[data-theme="dark"]{
  --bg:#14171a; --surface:#1c2023; --surface-2:#22272b;
  --ink:#f2f4f5; --ink-2:#b3bbc1; --ink-3:#8b949b;
  --rule:#2c3236;
  --accent:#6da7ec; --accent-2:#3987e5;
  --flag:#e66767; --ok:#3fae7f;
  --s1:#3987e5; --s2:#d95926; --s3:#199e70;
  --grid:#282e32; --event:#5a636a;
  color-scheme:dark;
}
*{box-sizing:border-box}
body{
  margin:0; background:var(--bg); color:var(--ink);
  font-family:"IBM Plex Sans",system-ui,-apple-system,"Segoe UI",sans-serif;
  font-size:16.5px; line-height:1.62; -webkit-font-smoothing:antialiased;
}
.page{
  display:grid;
  grid-template-columns:[full-start] minmax(20px,1fr) [main-start] min(68ch,calc(100% - 40px)) [main-end] minmax(20px,1fr) [full-end];
}
.page > *{grid-column:main}
/* Sections span the full width and re-expose the page's own column tracks via
   subgrid, so a figure or table nested inside a section can still break out of
   the prose column. Without this, `.wide` sits two levels down from the grid
   and never resolves against the named lines. */
.page > header,.page > section,.page > footer{
  grid-column:full; display:grid; grid-template-columns:subgrid;
}
/* max-width/auto-margins are the fallback: if a viewer lacks subgrid the
   section collapses to one full-width track, and these keep prose at a
   readable measure and wide blocks centred instead of spanning the viewport. */
.page > header > *,.page > section > *,.page > footer > *{
  grid-column:main; max-width:68ch; margin-inline:auto; width:100%;
}
.page > section > .wide{
  grid-column:full; justify-self:center; max-width:1060px; width:min(1060px,100%);
}
/* Dividers are drawn as main-column pseudo-elements rather than borders on the
   now-full-width sections, so the rule stays the width of the text. */
.page > section + section::before,.page > footer::before{
  content:""; grid-column:main; height:1px; background:var(--rule); margin:0 0 32px;
}
h1,h2,h3{font-family:"IBM Plex Serif",Georgia,serif; text-wrap:balance; margin:0}
h1{font-size:clamp(30px,5vw,44px); font-weight:600; line-height:1.14; letter-spacing:-.015em}
h2{font-size:26px; font-weight:600; letter-spacing:-.01em}
h3{font-size:18.5px; font-weight:600; margin:28px 0 6px}
p{margin:0 0 15px}
a{color:var(--accent)}
.eyebrow{
  font-family:"IBM Plex Mono",ui-monospace,monospace; font-size:11px;
  letter-spacing:.13em; text-transform:uppercase; color:var(--ink-3); margin:0 0 7px;
}
header.hd{padding:56px 0 16px}
.dek{font-size:19px; color:var(--ink-2); margin:15px 0 0}
.meta{
  font-family:"IBM Plex Mono",monospace; font-size:12px; color:var(--ink-3);
  margin-top:24px; padding-top:14px; border-top:1px solid var(--rule);
  display:flex; flex-wrap:wrap; gap:6px 22px;
}
section{padding:32px 0}
.stats{
  display:grid; grid-template-columns:repeat(auto-fit,minmax(142px,1fr));
  gap:1px; background:var(--rule); border:1px solid var(--rule); margin:24px 0 8px;
}
.stat{background:var(--surface); padding:16px 18px}
.stat b{
  display:block; font-family:"IBM Plex Mono",monospace; font-size:25px;
  font-weight:500; letter-spacing:-.02em; font-variant-numeric:tabular-nums; line-height:1.15;
}
.stat span{display:block; font-size:12.5px; color:var(--ink-3); margin-top:5px}
.verdicts{display:grid; gap:16px; grid-template-columns:repeat(auto-fit,minmax(285px,1fr)); margin:10px 0 4px}
.vc{background:var(--surface); border:1px solid var(--rule); padding:20px}
.vc h3{margin:11px 0 8px; font-size:19px}
.vc p{margin:0; font-size:15px; color:var(--ink-2)}
.chip{
  display:inline-block; font-family:"IBM Plex Mono",monospace; font-size:11px;
  letter-spacing:.09em; text-transform:uppercase; padding:4px 9px; border:1px solid currentColor;
}
.chip.no{color:var(--flag)} .chip.yes{color:var(--ok)} .chip.open{color:var(--ink-3)}
figure{margin:24px 0 6px; background:var(--surface); border:1px solid var(--rule); padding:16px 16px 12px}
figcaption{font-size:13.5px; color:var(--ink-2); margin-top:11px; line-height:1.5}
svg.chart{display:block; width:100%; height:auto}
.grid{stroke:var(--grid); stroke-width:1}
.tick{fill:var(--ink-3); font-family:"IBM Plex Mono",monospace; font-size:11px}
.ln{fill:none; stroke-width:2; stroke-linejoin:round; stroke-linecap:round}
.ln.s1{stroke:var(--s1)} .ln.s2{stroke:var(--s2)} .ln.s3{stroke:var(--s3)}
.bar.s1,.dot.s1{fill:var(--s1); stroke:none}
.event{stroke:var(--event); stroke-width:1.5; stroke-dasharray:4 4}
.event-label{fill:var(--ink-3); font-family:"IBM Plex Mono",monospace; font-size:10.5px}
.real{stroke:var(--flag); stroke-width:2.5}
.real-label{fill:var(--flag); font-family:"IBM Plex Mono",monospace; font-size:11.5px; font-weight:500}
.pt-label{fill:var(--ink-2); font-family:"IBM Plex Mono",monospace; font-size:10.5px}
.axis-title{fill:var(--ink-3); font-family:"IBM Plex Sans",sans-serif; font-size:11.5px}
.legend{display:flex; flex-wrap:wrap; gap:8px 18px; margin-top:12px; font-size:13px; color:var(--ink-2)}
.lg{display:inline-flex; align-items:center; gap:7px}
i.sw{width:14px; height:3px; border-radius:2px; display:inline-block}
i.sw.s1{background:var(--s1)} i.sw.s2{background:var(--s2)} i.sw.s3{background:var(--s3)}
.tw{overflow-x:auto; margin:18px 0; border:1px solid var(--rule); background:var(--surface)}
table{border-collapse:collapse; width:100%; font-size:14px}
th,td{text-align:left; padding:9px 12px; border-bottom:1px solid var(--rule); vertical-align:top}
th{
  font-family:"IBM Plex Mono",monospace; font-size:10.5px; letter-spacing:.08em;
  text-transform:uppercase; color:var(--ink-3); font-weight:500;
  background:var(--surface-2); white-space:nowrap;
}
tbody tr:last-child td{border-bottom:none}
td.n,th.n{text-align:right}
.n{font-family:"IBM Plex Mono",monospace; font-variant-numeric:tabular-nums; white-space:nowrap}
code,.mono{font-family:"IBM Plex Mono",monospace; font-size:.9em}
blockquote{
  margin:16px 0; padding:14px 18px; background:var(--surface);
  border-left:3px solid var(--accent-2); font-family:"IBM Plex Mono",monospace;
  font-size:13px; line-height:1.6; color:var(--ink-2);
}
.callout{margin:22px 0; padding:18px 20px; background:var(--surface); border:1px solid var(--rule); border-left:3px solid var(--flag)}
.callout p:last-child{margin-bottom:0}
.callout .eyebrow{color:var(--flag)}
.note{margin:22px 0; padding:18px 20px; background:var(--surface); border:1px solid var(--rule); border-left:3px solid var(--accent-2)}
.note p:last-child{margin-bottom:0}
.note .eyebrow{color:var(--accent)}
.fnote{font-size:13px; color:var(--ink-3); margin-top:-6px}
ul,ol{margin:0 0 15px; padding-left:22px}
li{margin-bottom:7px}
pre{
  background:var(--surface); border:1px solid var(--rule); padding:14px 16px;
  overflow-x:auto; font-family:"IBM Plex Mono",monospace; font-size:12.5px; margin:14px 0;
}
footer{padding:34px 0 64px; color:var(--ink-3); font-size:13px}
:focus-visible{outline:2px solid var(--accent-2); outline-offset:2px}
@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
"""


def main() -> None:
    cov = FINDINGS["coverage"]
    tp = FINDINGS["templating"]
    corr = FINDINGS.get("rate_templating_correlation", {})
    tmpl_pct = 100.0 * tp["complaints_in_templates"] / tp["narratives_scored"]
    by = FINDINGS["templated_share_by_month"]
    tops = top_templates(6)
    states = FINDINGS["state_rate_vs_templating"]

    def pct_at(seg: str, month: str = "2025-07"):
        row = by.get(seg, {}).get(month)
        return row["pct"] if row else None

    d: list[str] = []
    A = d.append

    A("<title>CFPB Complaint Templating</title>")
    A('<link rel="preconnect" href="https://fonts.googleapis.com">')
    A('<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>')
    A('<link rel="stylesheet" href="https://fonts.googleapis.com/css2?'
      "family=IBM+Plex+Mono:wght@400;500&"
      "family=IBM+Plex+Sans:wght@400;500;600&"
      'family=IBM+Plex+Serif:wght@500;600&display=swap">')
    A(f"<style>{CSS}</style>")

    A('<div class="page">')

    # ---------------- header ----------------
    A(f"""<header class="hd">
<p class="eyebrow">Southwest Public Policy Institute &middot; Data forensics</p>
<h1>Who is actually filing CFPB complaints?</h1>
<p class="dek">A census of all {cov['n']:,} consumer complaints in six product
segments of the CFPB Consumer Complaint Database, testing two claims: that
complaints are being filed at industrial scale from templates, and that the
volume surge followed public adoption of large language models.</p>
<div class="meta"><span>Extract {cov['first_date']} to {cov['last_date']}</span>
<span>{cov['narratives']:,} published narratives</span>
<span>{cov['companies']:,} respondent firms</span>
<span>Analysis run 2026-08-21</span></div>
</header>""")

    # ---------------- bottom line ----------------
    A("<section>")
    A('<p class="eyebrow">Bottom line</p>')
    A("<h2>Two claims, two different answers</h2>")
    A(f"""<div class="stats">
<div class="stat"><b>{tmpl_pct:.0f}%</b><span>of published narratives are byte-identical to at least 49 others</span></div>
<div class="stat"><b>{tp['complaints_in_templates']:,}</b><span>complaints reusing a text seen 50 or more times</span></div>
<div class="stat"><b>58% v 49%</b><span>relief rate on templated versus organic credit-reporting complaints</span></div>
<div class="stat"><b>0 of 7</b><span>segments where an LLM-date effect survives a placebo test</span></div>
</div>""")
    A(f"""<div class="verdicts">
<div class="vc"><span class="chip yes">Substantiated</span>
<h3>Templated mass filing</h3>
<p>{tp['complaints_in_templates']:,} complaints reuse one of {tp['template_texts']:,}
texts that each appear at least 50 times. The most-used single text appears
{tops[0]['size']:,} times, against {tops[0]['companies']} firms across
{tops[0]['states']} states. The pattern concentrates in credit reporting and debt
collection and is near-absent from every other segment.</p></div>
<div class="vc"><span class="chip no">Not supported</span>
<h3>LLM-driven complaint surge</h3>
<p>The headline series &mdash; credit reporting, cards, debt collection and the
combined total &mdash; all yield statistically significant coefficients, and
every one of the seven fails a placebo test. Templating climbs continuously from
2019 with no break at any milestone, and the estimated effect changes sign
across segments &mdash; positive for cards, negative for debt collection.</p></div>
</div>""")
    A("""<p>Those two answers are connected: whatever is producing the
templated filings was already operating years before ChatGPT existed, and it
explains the volume growth and the text patterns better than LLM adoption
does.</p>""")
    A("""<div class="note"><p class="eyebrow">What this does not say</p>
<p>Public data cannot name the intermediary. Identical text is equally
consistent with a paid credit-repair firm filing for a client book and with a
free script circulating on social media &mdash; the FCRA recitations below are
posted publicly at no cost. The distinction matters for remedy, because the
Credit Repair Organizations Act reaches paid organizations and nothing else.
Two signatures in the data lean toward organized operation &mdash; template
lifespans measured in years, and filings concentrated on business days &mdash;
but neither identifies anyone, and this report does not claim to.</p></div>""")
    A("</section>")

    # ---------------- what was examined ----------------
    A("<section>")
    A('<p class="eyebrow">The extract</p>')
    A("<h2>What was examined</h2>")
    A(f"""<p>Every complaint in six canonical product segments, from the first
record in the public database to the day of extraction &mdash;
{cov['n']:,} complaints, matching the API's own count for this scope exactly.
Not a sample.</p>""")
    rows = [
        [f"<code>{esc(r['segment'])}</code>",
         f"<span class='n'>{r['n']:,}</span>",
         esc(r['first_date']), esc(r['last_date'])]
        for r in FINDINGS["segments"]
    ]
    A(table(["Segment", "Complaints", "First", "Last"], rows))
    A(f"""<p>Of these, {cov['narratives']:,} carry a narrative the consumer
consented to publish &mdash; about {100 * cov['narratives'] / cov['n']:.0f}%.
Narratives are the only window onto who wrote a complaint, so every text finding
below describes that consenting subset, which is not a random sample of
complaints.</p>""")
    A('<figure class="wide">')
    A(build_volume_chart())
    A(legend([("Credit reporting", 1), ("All five other segments", 2)]))
    A("""<figcaption>Credit reporting alone accounts for 14.0 million of the
16.5 million complaints examined. It rises from roughly 100 complaints a month in
2012 to over 600,000 a month by mid-2026, while the five other segments combined
stay near 20,000. Log scale.</figcaption>""")
    A("</figure>")
    A("</section>")

    # ---------------- finding 1 ----------------
    A("<section>")
    A('<p class="eyebrow">Finding &middot; substantiated</p>')
    A("<h2>Complaints are being filed from templates at industrial scale</h2>")
    A(f"""<p>Of {tp['narratives_scored']:,} narratives long enough to compare
(25 words or more after normalisation), <strong>{tp['complaints_in_templates']:,}
&mdash; {tmpl_pct:.1f}% &mdash; are byte-identical to at least 49 other
narratives</strong>. They reuse {tp['template_texts']:,} distinct texts, each
appearing 50 or more times. A further {tp['exact_dup_any'] - tp['complaints_in_templates']:,}
narratives are exact duplicates in smaller groups.</p>""")
    A("""<p>These are exact duplicates after case, punctuation and
redaction-marker normalisation &mdash; not paraphrases, not "similar" text. That
matters for defensibility: the near-duplicate clustering described in the method
section can chain unlike documents together, so every headline count here uses
byte-identical grouping, where that failure mode cannot occur.</p>""")

    trows = []
    for t in tops:
        snippet = esc(t["text"][:190]) + ("&hellip;" if len(t["text"]) > 190 else "")
        trows.append([
            f"<span class='n'>{t['size']:,}</span>",
            f"<span class='n'>{t['companies']}</span>",
            f"<span class='n'>{t['states']}</span>",
            f"{esc(t['first'])} to {esc(t['last'])}",
            f"<span class='mono'>{snippet}</span>",
        ])
    A('<div class="wide">')
    A(table(["Copies", "Firms", "States", "Active", "Opening text"], trows))
    A("</div>")
    A("""<p class="fnote">State counts exceed 50 because CFPB's
<code>state</code> field also carries the District of Columbia, Puerto Rico and
other territories, and the military codes AA, AE and AP. Those values have no
Census population denominator and are excluded from the per-capita figures later
in this report.</p>""")

    A("""<h3>The templates coach filers to deny that a third party is involved</h3>
<p>CFPB's complaint form asks whether a third party is submitting on the
consumer's behalf. Several of the most-copied texts script a denial of exactly
that. One text, filed identically 14,558 times against 3 firms across 41
states, reads in full:</p>""")
    A("""<blockquote>I'm really not sure what happened. I have mailed off letters
to the credit bureaus continuously and thus far I have not gotten a response. My
name is XXXX XXXX and I am filing this complaint for falsely reporting misleading
information. <strong>There is no third party involved.</strong> PLease review the
uploaded letters.</blockquote>""")
    A("""<p>A near-duplicate family of roughly 10,500 complaints goes further,
scripting a declaration <em>under penalty of perjury</em> that the complaint is
not being made by a third party.</p>""")
    A("""<div class="note"><p class="eyebrow">Weigh this carefully</p>
<p>It is tempting to read a scripted denial of third-party involvement as an
agent lying. It is weaker than that. A consumer who copied a free script from a
video and filed it personally <em>is</em> telling the truth &mdash; no third
party submitted for them. What the template shows is that its author anticipated
CFPB's question and supplied an answer, which is a fact about the template's
provenance rather than proof of a false statement by any filer.</p></div>""")

    A("""<h3>The most-copied text is viral pseudolaw, not a description of harm</h3>
<p>The largest group is a recitation of statute rather than an account of
anything that happened to the filer:</p>""")
    A("""<blockquote>In accordance with the Fair Credit Reporting act. The List of
accounts below has violated my federally protected consumer rights to privacy
and confidentiality under 15 USC 1681. [redacted account list] 15 U.S.C 1681
section 602 A. States I have the right to privacy. 15 U.S.C 1681 Section 604 A
Section 2 : It also states a consumer reporting agency can&hellip;</blockquote>""")
    A("""<p>Other high-volume families cite <span class="mono">15 USC 1666b</span>
against late-payment reporting, invoke "estoppel by silence", or demand blocks
under FCRA 605B, the identity-theft provision. These are recognisable
credit-repair and sovereign-citizen argument templates. Their presence does not
establish that the underlying disputes are false &mdash; a real error can be
disputed with a bad template &mdash; but the filings are not independent
consumer accounts.</p>""")

    A("<h3>Templating is confined to the two credit-repair segments</h3>")
    srows = []
    for seg in ["credit_reporting", "debt_collection", "card",
                "consumer_loan", "student_loan", "mortgage"]:
        v = pct_at(seg)
        srows.append([
            esc(SEG_LABEL[seg]),
            f"<span class='n'>{v:.1f}%</span>" if v is not None else "&mdash;",
        ])
    A(table(["Segment", "Templated share of narratives, July 2025"], srows))
    A("""<p>This specificity is the strongest argument against the LLM
explanation. If consumers were using chatbots to draft complaints, templated
text would appear wherever consumers complain &mdash; mortgages, cards, student
loans. Instead it is 44% in credit reporting, 24% in debt collection, and
effectively zero in the other four. That is the footprint of an industry that
operates in credit disputes, not of a general-purpose writing tool.</p>""")

    A("<h3>Two signatures point to organised filing rather than viral scripts</h3>")
    A("""<p>Identical text cannot by itself distinguish a paid operation from a
free script that spread on social media. Two properties of the filings can,
without needing to identify anybody.</p>""")

    life = FOLLOWUPS.get("template_lifespan")
    if life:
        lrows = [
            [esc(r["band"]),
             f"<span class='n'>{r['templates']:,}</span>",
             f"<span class='n'>{r['complaints']:,}</span>"]
            for r in life
        ]
        A(table(["Template active for", "Templates", "Complaints"], lrows))
        long_lived = sum(r["complaints"] for r in life if r["band"] in
                         ("1-2 years", "over 2 years"))
        A(f"""<p><strong>Lifespan.</strong> A script that goes viral burns out;
a business runs for years. {long_lived:,} templated complaints &mdash; the
majority &mdash; come from templates in continuous use for more than a year, and
238 templates have been running for over two years. The median template of every
lifespan band is filed against exactly three firms, which are the three national
credit bureaus.</p>""")

    dow = FOLLOWUPS.get("day_of_week")
    if dow:
        drows = [
            [esc(day),
             f"<span class='n'>{dow['templated'][day]:.1f}%</span>",
             f"<span class='n'>{dow['organic'][day]:.1f}%</span>"]
            for day in ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
        ]
        A(table(["Day received", "Templated", "Organic"], drows))
        A(f"""<p><strong>Day of week.</strong> Templated credit-reporting
complaints arrive on weekends
{dow['templated_weekend_pct']}% of the time; organic ones
{dow['organic_weekend_pct']}% &mdash; roughly twice as often. People filing their
own grievances do it on Saturday; templated filings keep office hours. Across
{dow['n_templated']:,} templated and {dow['n_organic']:,} organic narratives,
this is the clearest provenance signal in the data that does not depend on
reading the text.</p>""")

    A("<h3>Three independent bureaus rose in lockstep</h3>")
    A("""<p>Through 2024, credit-reporting volume went from 101,735 to 267,923
complaints a month. Broken out by respondent, TransUnion rose 2.27&times;,
Experian 2.43&times; and Equifax 2.25&times; over the same twelve months.</p>
<p>Consumers filing individually, off whatever template they happened to find,
would not produce near-identical multipliers against three independent
companies. Software that submits the same dispute to all three at once
would &mdash; and submitting simultaneously to all three is what dispute
platforms do. This is the strongest institutional evidence in the report, and
unlike the text findings it rests on metadata that needs no narrative
consent.</p>""")

    A("<h3>Geography: high-filing states file more of everything</h3>")
    A('<figure class="wide">')
    A(build_state_chart())
    A(f"""<figcaption>Each point is a state: 2025 credit-reporting complaints per
100,000 residents against the share of that state's narratives that are
templated. Pearson r = {corr.get('pearson_r', '—')} across
{corr.get('n_states', '—')} states. <strong>This correlation is partly
arithmetic</strong> &mdash; see below. Hover any point for its
values.</figcaption>""")
    A("</figure>")
    hrows = []
    for r in states[:7]:
        hrows.append([
            esc(r["state"]),
            f"<span class='n'>{r['complaints_2025']:,}</span>",
            f"<span class='n'>{r['rate_per_100k_2025']:,.0f}</span>",
            f"<span class='n'>{r['templated_pct']:.1f}%</span>",
        ])
    # Explicit elision row: without it the jump from the top group to the
    # bottom group reads as a continuous ranking.
    omitted = len(states) - 11
    hrows.append([
        f"<span style='color:var(--ink-3)'>&hellip; {omitted} states omitted "
        f"&hellip;</span>", "", "", "",
    ])
    for r in states[-4:]:
        hrows.append([
            esc(r["state"]),
            f"<span class='n'>{r['complaints_2025']:,}</span>",
            f"<span class='n'>{r['rate_per_100k_2025']:,.0f}</span>",
            f"<span class='n'>{r['templated_pct']:.1f}%</span>",
        ])
    A(table(["State", "Complaints 2025", "Per 100k residents",
             "Templated share"], hrows))
    A("""<p>Georgia filed 3,430 credit-reporting complaints per 100,000 residents
in 2025. Wyoming filed 131 &mdash; a 26-fold difference between US states under
the same federal credit-reporting law, with the high-rate states forming a
contiguous Deep South and Gulf cluster.</p>""")

    gs = FOLLOWUPS.get("geo_split_stats")
    grows = FOLLOWUPS.get("geo_split")
    if gs and grows:
        A("""<div class="callout"><p class="eyebrow">Correction to an earlier
reading of this result</p>
<p>Templated complaints sit <em>inside</em> the numerator of the filing rate, so
a state with heavy templating is mechanically a high-rate state. Part of the
0.653 correlation above is therefore arithmetic rather than evidence. The test
that removes it is to rate templated and organic narratives separately.</p>
</div>""")
        srows = []
        for r in (grows[:5] + grows[-4:]):
            ratio = r["templated_per_100k"] / max(r["organic_per_100k"], 0.01)
            srows.append([
                esc(r["state"]),
                f"<span class='n'>{r['templated_per_100k']:,.0f}</span>",
                f"<span class='n'>{r['organic_per_100k']:,.0f}</span>",
                f"<span class='n'>{ratio:.2f}</span>",
            ])
        A('<div class="wide">')
        A(table(["State", "Templated narratives per 100k",
                 "Organic narratives per 100k", "Ratio"], srows))
        A("</div>")
        A(f"""<p>Separated, the two rates correlate at
<strong>{gs['correlation_templated_vs_organic']}</strong>. Organic narrative
filing on its own varies {gs['organic_max_min_ratio']}&times; across states;
templated filing varies {gs['templated_max_min_ratio']}&times;. So the enormous
geographic dispersion is <em>not</em> mainly a templating phenomenon: states that
file a lot file a lot of both kinds. Georgia, the highest-rate state, is actually
<em>under</em>-templated relative to its organic volume (ratio 0.79), while
Alabama at 1.56 is the clearest genuine skew.</p>
<p>This weakens the geographic argument considerably, and it should. The
straightforward rival explanation &mdash; that Alabama, Mississippi and Louisiana
have among the worst credit-score distributions in the country and therefore the
most genuine disputes to file &mdash; predicts exactly this pattern of elevated
filing across both categories. What survives is narrower: a modest templating
excess in a handful of Gulf states, not a geographic fingerprint of coordinated
filing.</p>""")
    A("</section>")

    # ---------------- does it work ----------------
    rel = FOLLOWUPS.get("relief", {})
    cr24 = rel.get("credit_reporting_2024", {})
    dc24 = rel.get("debt_collection_2024", {})
    if cr24:
        A("<section>")
        A('<p class="eyebrow">Outcome</p>')
        A("<h2>Templated filings get results &mdash; more of them</h2>")
        A("""<p>The obvious next question is whether any of this works.
<code>company_response</code> records how each complaint closed, so relief rates
for templated and organic filings can be compared directly.</p>""")
        rrows = []
        for label, key, data in [
            ("Credit reporting 2024", "cr", cr24),
            ("Debt collection 2024", "dc", dc24),
        ]:
            for kind in ("templated", "organic"):
                v = data.get(kind)
                if not v:
                    continue
                rrows.append([
                    esc(f"{label} — {kind}"),
                    f"<span class='n'>{v['n']:,}</span>",
                    f"<span class='n'>{v['relief_pct']:.1f}%</span>",
                    f"<span class='n'>{v['monetary_pct']:.3f}%</span>",
                    f"<span class='n'>{v['explanation_pct']:.1f}%</span>",
                ])
        A('<div class="wide">')
        A(table(["Series", "Closed complaints", "Any relief",
                 "Monetary relief", "Explanation only"], rrows))
        A("</div>")
        A(f"""<p>Templated credit-reporting complaints obtained relief
{cr24['templated']['relief_pct']:.1f}% of the time against
{cr24['organic']['relief_pct']:.1f}% for organic ones. In debt collection the
gap is far wider: {dc24['templated']['relief_pct']:.1f}% against
{dc24['organic']['relief_pct']:.1f}%, a factor of
{dc24['templated']['relief_pct'] / max(dc24['organic']['relief_pct'], 0.01):.1f}.
Monetary relief is negligible either way &mdash; well under a tenth of a percent
&mdash; so essentially all of this is <em>non-monetary</em> relief, which in
credit reporting means a tradeline was deleted or corrected.</p>""")
        A("""<div class="callout"><p class="eyebrow">This cuts two ways, and the
data cannot say which</p>
<p>Reading one: mass templated disputes work precisely because a bureau facing
industrial dispute volume cannot verify each item inside the statutory window,
so contested entries get deleted whether or not they were wrong. That is the
credit-washing concern, and it would explain why the practice is profitable
enough to sustain templates for years.</p>
<p>Reading two: the disputes are largely meritorious, and templating is simply
consumers using an effective form of words for real errors.</p>
<p>Nothing in the public data distinguishes them, because the file records that
an item was removed, never whether removing it was correct. But the result does
rule out the tidiest version of a consumer-protection story &mdash; these filings
are not consumers paying for something that does nothing. Whatever else is true,
templated disputes are the <em>more</em> effective instrument.</p></div>""")
        A("</section>")

    # ---------------- finding 2 ----------------
    A("<section>")
    A('<p class="eyebrow">Finding &middot; not supported</p>')
    A("<h2>The LLM-adoption hypothesis does not survive testing</h2>")
    A("""<p>An interrupted time-series regression was fitted at three LLM
milestones &mdash; ChatGPT's public launch (2022-11-30), its mass-adoption point
(2023-01-31), and GPT-4's release (2023-03-14) &mdash; on monthly complaint
counts, using a negative binomial model because the counts are heavily
overdispersed.</p>""")
    A("""<p>Taken at face value, the results for the high-volume series look
like a confirmation. Credit reporting shows a +21.8% level shift at ChatGPT's
launch with p = 0.010; the combined series shows +36.1% with p below 0.001;
slope-change p-values are effectively zero. Reported on their own, these would
read as a clear finding. (Mortgages, student loans and consumer loans return no
significant coefficient at all &mdash; see the table below.)</p>""")
    A("""<div class="callout"><p class="eyebrow">The trap</p>
<p>The complaint series grows steeply and non-linearly across its entire life,
long before any LLM existed. A segmented regression fitted to a curve like that
returns a large, significant "level shift" at almost <em>any</em> date, because
the break term absorbs ordinary curvature. The p-value is real; the
interpretation is not.</p></div>""")
    A("""<p>Each estimate was therefore compared against a placebo distribution:
the identical model refitted at every other candidate date in the series, at
least twelve months from either end and excluding dates within six months of the
real one. If the effect at the real date is unremarkable against that
distribution, there is no effect to report regardless of its p-value.</p>""")
    A('<figure class="wide">')
    A(build_placebo_charts()[0])
    A("""<figcaption>Credit reporting. Each bar counts placebo dates producing an
absolute level-change estimate of that size; the red line marks the estimate at
ChatGPT's launch. It sits at the 28th percentile &mdash; 93 of 129 dates where
nothing relevant happened produce a larger effect.</figcaption>""")
    A("</figure>")

    irows = []
    for seg, months, lvl, p, pctile, verdict in ITS:
        chip = ("<span class='chip open'>suggestive</span>"
                if verdict == "suggestive"
                else "<span class='chip no'>not distinctive</span>")
        label = SEG_LABEL.get(seg, seg)
        irows.append([
            esc(label),
            f"<span class='n'>{months}</span>",
            f"<span class='n'>{lvl:+.1f}%</span>",
            f"<span class='n'>{p}</span>",
            f"<span class='n'>{ordinal(pctile)}</span>",
            chip,
        ])
    A('<div class="wide">')
    A(table(["Segment", "Months", "Level change at ChatGPT launch", "p",
             "Placebo percentile", "Verdict"], irows))
    A("</div>")
    A("""<p>Two things in that table settle it. First, no segment clears the
placebo distribution. Second, <strong>the sign of the effect flips across
segments</strong>: +34.8% for cards, &minus;22.1% for debt collection,
&minus;6.5% for mortgages. A technology that made it easier for consumers to
write complaints would push every consumer-facing segment the same direction. A
mix of positive and negative "highly significant" effects is the signature of a
model fitting six unrelated growth curves.</p>""")

    A("<h3>Where the real breaks are</h3>")
    A("""<p>Changepoint detection was run blind &mdash; searching for structural
breaks without being told the LLM dates &mdash; so agreement with a milestone
would be evidence rather than assumption. None of the largest breaks land on
one.</p>""")
    brows = [
        [esc(SEG_LABEL.get(s, s)), esc(m), f"<span class='n'>{c}</span>", esc(why)]
        for s, m, c, why in BREAKS
    ]
    A('<div class="wide">')
    A(table(["Segment", "Break", "Change", "Nearest known cause"], brows))
    A("</div>")
    A("""<p>The student-loan case shows why the registry of competing events
matters. Its +214% break at 2023-06 sits 79 days from GPT-4's release &mdash;
and 29 days from <em>Biden v. Nebraska</em>, the Supreme Court decision striking
down loan forgiveness. Attributing that break to LLM adoption would have been a
straightforward error.</p>""")

    A("<h3>The honest exception: cards</h3>")
    A(f"""<p>Cards is the one segment where the placebo test does not dismiss the
LLM dates. Its +34.8% level shift sits at the 82nd percentile of placebo
effects, and the same pattern holds at the other two milestones (84th and 89th).
The skill's own verdict for this is "suggestive: larger than most placebo dates
but inside the range the series produces on its own".</p>""")
    A("""<p>Two things argue against reading it as an LLM effect anyway. The
segment's detected changepoint is 2022-10, which <em>precedes</em> ChatGPT's
launch by about sixty days &mdash; a break cannot be caused by an event that has
not happened yet. And card narratives are only 1.3% templated, so whatever drove
the volume is not producing duplicated text. This is the strongest pro-hypothesis
evidence in the data, and it is weak.</p>""")

    A("<h3>Templating predates the LLMs by three years</h3>")
    A('<figure class="wide">')
    A(build_templating_chart())
    A(legend([("Credit reporting", 1), ("Debt collection", 2),
              ("Other four segments", 3)]))
    A("""<figcaption>Share of narratives byte-identical to at least 49 others.
Credit reporting climbs from under 1% in 2016 through 18% by October 2022
&mdash; before ChatGPT &mdash; to about 50% by late 2025. The trend is
continuous through the launch line. Months with fewer than 150 scorable
narratives are omitted.</figcaption>""")
    A("</figure>")
    A("""<p>This is the clearest single refutation. If LLMs had driven templated
complaint filing, the curve would inflect at the launch line. It does not: it
begins rising in 2019 and continues at the same trajectory across it. Note too
that LLM assistance would <em>reduce</em> exact duplication, since a chatbot
paraphrases rather than copies. That nearly half of 2025 narratives are literal
copies indicates bulk filing is still copy-and-paste.</p>""")
    A("</section>")

    # ---------------- channel ----------------
    A("<section>")
    A('<p class="eyebrow">Provenance</p>')
    A("<h2>The surge is almost entirely web-filed</h2>")
    A("""<p><code>submitted_via</code> is the closest thing the public data has
to a provenance field. Comparing the 18 months before ChatGPT's launch with the
18 months after:</p>""")
    crows = []
    for name, pre, post, pres, posts in CHANNEL:
        chg = (post / pre - 1) * 100 if pre else 0
        crows.append([
            esc(name),
            f"<span class='n'>{pre:,}</span>",
            f"<span class='n'>{post:,}</span>",
            f"<span class='n'>{chg:+.1f}%</span>",
            f"<span class='n'>{pres:.2f}% &rarr; {posts:.2f}%</span>",
        ])
    A('<div class="wide">')
    A(table(["Channel", "18 months before", "18 months after", "Change",
             "Share of filings"], crows))
    A("</div>")
    A("""<p>Web filings rose 136% while phone filings rose 7.9% and referrals
fell 54%. Web share went from 95.1% to 98.0%. A broad increase in genuine
consumer harm should lift the non-web channels too, at least somewhat.</p>""")
    A("""<p>This constrains interpretation without settling it. Bulk automated or
brokered filing can only realistically scale the web channel &mdash; but so does
ordinary continued migration of consumers to online forms. The signal is
consistent with the templating evidence rather than independent of it.</p>""")
    A("</section>")

    # ---------------- bursts ----------------
    A("<section>")
    A('<p class="eyebrow">Controls</p>')
    A("<h2>The biggest volume spikes are corporate events, not campaigns</h2>")
    A("""<p>Per-firm burst detection scores each company-month against that
company's own trailing 12-month median. The largest spikes in the data are all
explained by servicer transfers and enforcement actions &mdash; which is exactly
why they are catalogued rather than reported as findings.</p>""")
    brows2 = [
        [esc(e), esc(m), f"<span class='n'>{x}</span>", esc(why)]
        for e, m, x, why in BURSTS
    ]
    A('<div class="wide">')
    A(table(["Entity", "Month", "Above own baseline", "Cause"], brows2))
    A("</div>")
    A("""<p>Two involve credit-repair and debt-relief firms &mdash; <strong>John
C Heath, Attorney at Law</strong>, which operates as Lexington Law, at 228 times
its baseline in December 2024, and <strong>Ameritech Financial</strong>, a
student debt-relief operation, at 164 times baseline in July 2018.</p>""")
    A("""<div class="note"><p class="eyebrow">Read the direction of these
carefully</p>
<p>The company field names the <em>respondent</em>, not the filer. These are
complaints <strong>against</strong> the credit-repair firms, from their own
customers &mdash; not evidence of those firms filing anything. A December 2024
example, in the consumer's words:</p></div>""")
    A("""<blockquote>I started doing business with Lexington Law a few months
ago. The company is charging me for services that they are not providing. My
[score] is going down, and they are disputing positive items causing my credit
report score to decrease.</blockquote>""")
    A("""<p>That belongs with the outcome question above rather than here: it is
a customer of a paid credit-repair firm reporting that the firm disputed
<em>accurate positive</em> entries on their file. The December 2024 spike is
plausibly a wind-down of the Progrexion group following its 2023 judgment, but
that is a hypothesis this dataset cannot confirm &mdash; it shows the complaints,
not the corporate cause.</p>""")
    A("</section>")

    # ---------------- method ----------------
    A("<section>")
    A('<p class="eyebrow">Method</p>')
    A("<h2>Five guardrails that changed the answer</h2>")
    A("""<p>Each of the following was capable of producing a false positive on
its own. They are documented because the headline conclusion depends on them,
not as generic caveats.</p>""")

    A("<h3>1. CFPB renamed its product categories inside the test window</h3>")
    A("""<p>The credit-reporting segment exists under three different
<code>product</code> labels. The current one, holding 11.7 million complaints,
begins 2023-08-24 &mdash; nine months after ChatGPT's launch. Grouped on the raw
field, a 2.2-million-complaint series collapses to zero while an 11.7-million one
appears from nothing, squarely inside the window under test.</p>""")
    rp = [
        [f"<span class='mono'>{esc(r['product'])}</span>",
         f"<span class='n'>{r['n']:,}</span>",
         f"{esc(r['first_seen'][:7])} to {esc(r['last_seen'][:7])}"]
        for r in FINDINGS["raw_product_windows"]
        if r["segment"] == "credit_reporting"
    ]
    A('<div class="wide">')
    A(table(["Raw product label", "Complaints", "Active"], rp))
    A("</div>")
    A("""<p>All series are therefore grouped on a canonical segment crosswalk,
never the raw label. The renames are provably administrative: credit reporting,
cards and consumer loans all switch labels on the same two dates, 2017-04-24 and
2023-08-24. <strong>The crosswalk fixes only half the problem</strong> &mdash; it
removes the break caused by a label changing, but not a change in what the
category covers. The 2017 rename genuinely broadened scope, and a +285% break
sits one week after it.</p>""")

    A("<h3>2. Placebo distributions, not p-values</h3>")
    A("""<p>Described above. Without this test, seven "significant" LLM effects
would have been reported as findings; none survives it.</p>""")

    A("<h3>3. Redaction inflates apparent similarity</h3>")
    A("""<p>CFPB replaces names, dates and addresses with runs of X, so unrelated
complaints share tokens purely through scrubbing. Redaction runs are collapsed to
a dropped sentinel before comparison, and each cluster reports the share of its
tokens that were redacted, so clusters that are similar only because they are
mostly redacted can be discarded.</p>""")

    A("<h3>4. Near-duplicate clusters chain, so they are not copy counts</h3>")
    A("""<p>Near-duplicate clustering links 2.03 million of 3.26 million
narratives at Jaccard 0.8. That number is <em>not</em> template membership.
Clusters are connected components under single linkage, so A joins C whenever
some B resembles both. Auditing the largest component found pairwise similarity
between members ranging from 0.36 to 1.00 against a 0.80 threshold &mdash; a
family of boilerplate variants sharing an opening paragraph, not one document
repeated.</p>
<p>Cluster exports therefore report <code>chained_size</code> rather than
"copies", alongside a cohesion measure sampled per cluster: the share of members
that actually meet the similarity threshold against the cluster's exemplar.</p>""")

    coh = cohesion_summary()
    if coh:
        crows = [
            [esc(b["band"].title()), esc(b["note"]),
             f"<span class='n'>{b['clusters']:,}</span>",
             f"<span class='n'>{b['complaints']:,}</span>"]
            for b in coh["bands"]
        ]
        A('<div class="wide">')
        A(table(["Cohesion band", "Members meeting threshold", "Clusters",
                 "Complaints"], crows))
        A("</div>")
        A(f"""<p>Across the {coh['measured']:,} clusters of ten or more,
<strong>{coh['tight_clusters']:,} are tight and cover
{coh['tight_complaints']:,} complaints</strong> &mdash; genuine reuse of a
single document. The measure earns its place at the top of the size ranking: the
two largest components, at 64,130 and 44,886 members, score cohesion of just 2.6%
and 5.1% and are chains rather than templates, while components of 19,677 and
19,506 members score 100% and are exactly what they appear to be.</p>
<p>So the defensible near-duplicate figure is roughly
{coh['tight_complaints'] / 1000:.0f},000 complaints in tightly-cohesive
clusters, against {tp['complaints_in_templates']:,} in exact-duplicate groups.
The two overlap heavily; the near-duplicate pass additionally catches
lightly-edited variants that byte-identical matching misses. Every headline
figure in this report uses the exact-duplicate count, which needs no cohesion
caveat at all.</p>""")

    A("<h3>5. Narrative publication collapses in 2026</h3>")
    A("""<p>Credit-reporting narrative coverage falls from about 25% to
<strong>0.1&ndash;3% from January 2026</strong>, while mortgage holds 28&ndash;46%
in the same months &mdash; so it is not ordinary publication lag. Text analysis
has effectively no coverage of 2026, and a null template result there would mean
"no text to compare", not "no templating". The 2026 period is excluded from every
text-based figure here.</p>""")
    A("</section>")

    # ---------------- limits ----------------
    A("<section>")
    A('<p class="eyebrow">Limits</p>')
    A("<h2>What this analysis does not establish</h2>")
    A("""<ul>
<li><strong>Not that the underlying disputes are false.</strong> A templated
complaint can describe a real credit-reporting error. Templating is evidence
about <em>provenance</em> &mdash; who drafted and filed the document &mdash; not
about the merits of the grievance.</li>
<li><strong>Not that any specific firm orchestrated filings.</strong> The
company field names the <em>respondent</em>, not the filer. Nothing in the public
data identifies the intermediary that distributed a template.</li>
<li><strong>Not that LLMs play no role.</strong> Exact-duplicate matching is
blind to paraphrase. LLM-assisted drafting would produce formulaic but unique
text, which this method cannot see and which would show up as a
<em>decline</em> in exact duplication. The finding is that LLM adoption does not
explain the volume or templating trends, not that no filer uses a chatbot.</li>
<li><strong>Narratives are a consenting subset.</strong> Roughly 21% of
complaints have a published narrative, and consent is unlikely to be random with
respect to whether a template was used.</li>
<li><strong>Cross-rename comparisons are not like-for-like</strong> for credit
reporting, per guardrail 1.</li>
<li><strong>Geographic resolution is regional.</strong> ZIP codes are truncated
to three digits, so concentration measures cannot reach neighbourhood
level.</li>
</ul>""")
    A("</section>")

    # ---------------- open questions ----------------
    A("<section>")
    A('<p class="eyebrow">Open</p>')
    A("<h2>Questions worth pursuing next</h2>")
    A("""<p><strong>The 2024 ramp is unexplained and it is the largest feature in
the database.</strong> Credit-reporting volume went from 101,735 to 267,923
complaints a month over twelve months, with TransUnion, Experian and Equifax
rising 2.27x, 2.43x and 2.25x &mdash; near-lockstep across independent
respondents, which points at filing-side behaviour rather than any one firm's
conduct. Nothing in the confounding-events registry accounts for it.</p>""")
    A("""<p><strong>The 2026 narrative blackout is a finding, not just a
limitation.</strong> Credit-reporting narrative publication fell to 0.1&ndash;3%
from January 2026 and stayed there for seven months, while mortgage held
28&ndash;46% across the same period. A processing backlog does not select one
product segment and spare another. Something changed in how the largest category
of complaints is published, and it is worth putting to CFPB directly: if it is a
backlog, 2026 will backfill and become analysable; if it is a policy change, the
provenance question becomes unanswerable going forward.</p>""")
    A("""<p>For the avoidance of doubt, this is not complaints stopping.
Daily filing continues at 24,000&ndash;29,000 on weekdays through mid-August
2026, and the taper over the final six days of the extract matches the ordinary
backfill lag rather than any cessation.</p>""")
    A("""<p><strong>Two intermediary firms show unexplained spikes</strong>
(Lexington Law's law firm, Ameritech Financial) and both are the kind of entity
this analysis is about.</p>""")
    A("""<p><strong>Sub-product series would give constant-scope comparisons</strong>
across the 2017 and 2023 renames, which is the one structural weakness left in
the volume analysis.</p>""")
    A("</section>")

    # ---------------- repro ----------------
    A("<section>")
    A('<p class="eyebrow">Reproducing this</p>')
    A("<h2>Every figure regenerates from the raw API</h2>")
    A("""<p>The extract is rebuilt by date-windowed CSV export against the public
API, with no key required. A full pull is roughly 16.5 million complaints and
about 4.5&nbsp;GB over the wire.</p>""")
    A("""<pre>python cli.py probe        # verify API, dump the live taxonomy, size the pull
python cli.py fetch        # windowed pull into local SQLite, resumable
python cli.py status       # coverage, rename diagnostics, narrative coverage
python cli.py its          # segmented regression, changepoints, placebo tests
python cli.py dedupe       # exact and near-duplicate narrative analysis
python cli.py bursts       # per-firm volume bursts and channel shift
python cli.py geo          # per-capita rates and concentration
python collect_findings.py # gather statistics into out/findings.json
python report_page.py      # render this page</pre>""")
    A("""<p>Population denominators come from Census Bureau state estimates for
the year each complaint was received. Competing-event dates are verified against
primary sources and carry citation URLs in
<code>cfpb_inspect/config.py</code>.</p>""")
    A("</section>")

    A("""<footer><p>Southwest Public Policy Institute. Analysis of the CFPB
Consumer Complaint Database, extract dated 2026-08-20, covering
2011-12-01 to 2026-08-19. Complaint narratives quoted above are published
public records, redacted by CFPB.</p></footer>""")
    A("</div>")

    out = config.OUT_DIR / "report.html"
    out.write_text("\n".join(d), encoding="utf-8")
    print(f"wrote {out}  ({out.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
